### ISSUE TITLE
use on https:// sites

### ISSUE THREAD

**Issue by RebafC** [andrezrv/follet-core#1]
When referencing schema.org in follet-template-tags.php, the HTTP protocol is hardcoded (i.e. http://schema.org). This means a security warning is triggered in the browser when the template is used on a secure site. If the protocol is dropped in the script so that schema.org is referenced as //schema.org instead, the site will be accessed using the protocol of the current request. If the current request uses https:// then the security warning will not be triggered.

**Comment by andrezrv** [comment]
Hi there! You're totally right. I just fixed this in the master branch (see b0e22990b6) and I will submit it to the WP directory as soon as possible. Thank you!
